### ISSUE TITLE
Permutation Generation documentation

### ISSUE THREAD

**Issue by cwidhelm** [jsa2/caOptics#14]
Can you update the documentation to include the name of the file that needs to be used to generate the visualization when using JSON Crack?

https://github.com/jsa2/caOptics?tab=readme-ov-file#permutation-generation

**Comment by jsa2** [comment]
Hi! Great question. I took the permutations from runtime dump, the file can be quite large, and I am not sure the visualization will work in larger environment. I will give it a test next week, and feature for you to test. --ListPermutations could be the switch, and it should write .json file for visualization

**Comment by jsa2** [comment]
Allocating some time this week to check how to do this

**Comment by CravateRouge** [comment]
I also noticed JSON Crack non premium is quickly size limited. 

The visualizer is definitely a game changer but could you make an alternative format for another tool which would be usable for non premium users?

**Comment by jsa2** [comment]
Hi, sorry for delay on my side. I've been focusing lately on few other things. So have not had time the full time to be active on this project, and will set the project to non-develop /archival status due to shifting priorities

**Comment by jsa2** [comment]
there is existing option to help with policy structure using --dump as cmdline arg
