### ISSUE TITLE
Does not work with gov environments yet

### ISSUE THREAD

**Issue by SamErde** [jsa2/caOptics#4]
The Graph API endpoints and authentication URIs are coded to use the worldwide instances at `[*.]microsoft.com`, which prevents customers in other instances from using the tool. GCC and GCC-HIGH use the `graph.microsoft.us` endpoint and `login.microsoftonline.us` authentication endpoint. It would be great to offer a parameter to choose the relevant Azure instance/environment name and update these endpoints accordingly. 

In my testing so far, I have been working around this with a search-replace of those two sets of strings, and also creating my initial connection with the following additional `az login` options before continuing: 

```AZ Shell
az cloud set --name AzureUSGovernment
az login --tenant <TENANT_ID>
```

I can fork with my edits, or go into a new branch if you'd like to create that at this time.

**Comment by jsa2** [comment]
Thx for the feedback! It is good idea to incorporate the login option as update to the readme.md - I have added new params to 0.6.6, that should allow using alternative endpoints (FQDN) https://github.com/jsa2/caOptics/tree/0.6.6#release-notes. These would be incorporated to main once they are tested in with the GCC tenant type
.

**Comment by SamErde** [comment]
Thanks, I'll be sure to test that branch soon! 

Also noted: it seems that the `userRiskLevel` condition is not returned in the GCCH environment that we tested. The policy evaluation was able to complete after commenting out the filter `&& s.conditions?userRiskLevels` [here](https://github.com/jsa2/caOptics/blob/6c698f1c1a3478de46753940bba1aaccefbe91e6/ca/mainPlugins/getPol.js#L321).

My working filter in **getPol.js** looks like: 
```
    p = data?.value.filter(s =>
        s?.state == 'enabled'
        && s.conditions.applications?.includeApplications.length > 0
        && s.grantControls?.builtInControls
        // && s.conditions?.userRiskLevels?.length == 0
        && s.conditions?.signInRiskLevels?.length == 0
    )
```

**Comment by jsa2** [comment]
I updated main branch with changes in "0.6.7"

Parameters reference includes some examples. Appreciate if you can test with the new params 

(some typos there, will be fixed later :) )

![image](https://user-images.githubusercontent.com/58001986/197490591-1dc9a3c4-3724-4572-bbe8-5e0ddb5a8b9f.png)

**Comment by SamErde** [comment]
Sorry for the much delayed response! I had made good progress on testing here, but then had to start on a fresh laptop and lost my notes and customizations. This error suggests I probably missed something. Any thoughts?
![image](https://user-images.githubusercontent.com/20478745/217053416-79d55b22-40ca-4fa1-b49f-bb8df96f6241.png)

**Comment by SamErde** [comment]
Oh, I just turned off `--debug` and it ran successfully with `node ./ca/main.js`, so I must have a misconfigured debugger in VS Code! Here's my current `launch.json`:  

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
"program": "${workspaceFolder}/ca/main.js",
//"program": "${file}",
            "args":  [
              "--altGraph=graph.microsoft.us",
              "--altLogin=login.microsoftonline.us",
              "--customPolicyFilter",
              "--skipObjectId=259fcf40-ff7c-4625-9b78-cd11793f161f",
              "--mapping",
              "--clearMappingCache",
              "--clearPolicyCache",
              "--clearTokenCache",
              // "--allowPreviewPolicies=beta",
              // "--allPlatforms",
              // "--includeReportOnly",
              // "--inject",
              // "--clearPolicyCache",
              // "--skipCleaning",
              // "--allTerminations",
              // "--aggressive",
              // "--debug",
            ],
            "runtimeArgs": [
                "--max-old-space-size=4096"
            ]
        }
    ]
  }
```

**Comment by jsa2** [comment]
Thx for testing! Feel free to ping back on any MSG:ng platform for any deeper look into the mechanics
